from __future__ import annotations

from typing import Protocol

from tabletop_companion.application.local_ports import LocalMultiplayerUnitOfWork
from tabletop_companion.domain.combat import (
    Combat,
    Combatant,
    DiceRoll,
    EventCompensation,
    MonsterTemplate,
)
from tabletop_companion.domain.events import DomainEvent


class CombatUnitOfWork(LocalMultiplayerUnitOfWork, Protocol):
    def add_combat(self, combat: Combat) -> None: ...

    def get_combat(self, combat_id: str) -> Combat: ...

    def get_active_combat(self, session_id: str) -> Combat | None: ...

    def list_combats(self, session_id: str) -> list[Combat]: ...

    def save_combat(self, combat: Combat) -> None: ...

    def add_monster_template(self, template: MonsterTemplate) -> None: ...

    def get_monster_template(self, template_id: str) -> MonsterTemplate: ...

    def list_monster_templates(self, room_id: str) -> list[MonsterTemplate]: ...

    def add_combatant(self, combatant: Combatant) -> None: ...

    def get_combatant(self, combatant_id: str) -> Combatant: ...

    def list_combatants(self, combat_id: str) -> list[Combatant]: ...

    def save_combatant(self, combatant: Combatant) -> None: ...

    def delete_combatants_for_entry(self, combat_id: str, entry_id: str) -> None: ...

    def add_dice_roll(self, roll: DiceRoll) -> None: ...

    def get_dice_roll(self, roll_id: str) -> DiceRoll: ...

    def save_dice_roll(self, roll: DiceRoll) -> None: ...

    def list_dice_rolls(self, combat_id: str) -> list[DiceRoll]: ...

    def get_event(self, event_id: str) -> DomainEvent: ...

    def add_event_compensation(self, compensation: EventCompensation) -> None: ...

    def get_event_compensation(self, event_id: str) -> EventCompensation | None: ...
