from __future__ import annotations

from typing import Protocol

from tabletop_companion.application.ports import UnitOfWork
from tabletop_companion.domain.access import LocalDevice, PairingInvitation, RoomInvitation
from tabletop_companion.domain.combat import DiceRoll
from tabletop_companion.domain.events import DomainEvent
from tabletop_companion.domain.models import Character, GmNotes, LocalPlayer, NpcNote, Room
from tabletop_companion.domain.sessions import GameSession


class LocalMultiplayerUnitOfWork(UnitOfWork, Protocol):
    def get_room_by_code(self, room_code: str) -> Room: ...

    def save_local_player(self, player: LocalPlayer) -> None: ...

    def list_local_players(self, room_id: str) -> list[LocalPlayer]: ...

    def list_characters_for_player(self, player_id: str) -> list[Character]: ...

    def list_characters_for_room(self, room_id: str) -> list[Character]: ...

    def add_dice_roll(self, roll: DiceRoll) -> None: ...

    def list_room_dice_rolls(self, room_id: str) -> list[DiceRoll]: ...

    def get_gm_notes(self, room_id: str) -> GmNotes | None: ...

    def add_gm_notes(self, notes: GmNotes) -> None: ...

    def save_gm_notes(self, notes: GmNotes) -> None: ...

    def list_npc_notes(self, room_id: str) -> list[NpcNote]: ...

    def get_npc_note(self, npc_id: str) -> NpcNote: ...

    def add_npc_note(self, note: NpcNote) -> None: ...

    def save_npc_note(self, note: NpcNote) -> None: ...

    def delete_npc_note(self, npc_id: str) -> None: ...

    def add_pairing_invitation(self, invitation: PairingInvitation) -> None: ...

    def get_pairing_by_token_digest(self, digest: str) -> PairingInvitation: ...

    def get_pairing(self, invitation_id: str) -> PairingInvitation: ...

    def get_pairing_by_short_code_digest(self, digest: str) -> PairingInvitation: ...

    def save_pairing_invitation(self, invitation: PairingInvitation) -> None: ...

    def revoke_pairing_invitations(self, room_id: str, revoked_at: str) -> int: ...

    def add_room_invitation(self, invitation: RoomInvitation) -> None: ...

    def get_room_invitation_by_digest(self, digest: str) -> RoomInvitation: ...

    def get_room_invitation(self, invitation_id: str) -> RoomInvitation: ...

    def save_room_invitation(self, invitation: RoomInvitation) -> None: ...

    def add_local_device(self, device: LocalDevice) -> None: ...

    def get_device(self, device_id: str) -> LocalDevice: ...

    def get_device_by_credential_digest(self, digest: str) -> LocalDevice: ...

    def save_local_device(self, device: LocalDevice) -> None: ...

    def list_local_devices(self, room_id: str) -> list[LocalDevice]: ...

    def add_game_session(self, session: GameSession) -> None: ...

    def get_game_session(self, session_id: str) -> GameSession: ...

    def get_unfinished_session(self, room_id: str) -> GameSession | None: ...

    def save_game_session(self, session: GameSession) -> None: ...

    def list_events_after(self, room_id: str, cursor: int, limit: int) -> list[DomainEvent]: ...

    def list_events_by_command(self, command_id: str) -> list[DomainEvent]: ...

    def event_cursor_bounds(self, room_id: str) -> tuple[int | None, int]: ...
